# ThoughtSpot_Administration_Guide_x.x
# ThoughtSpot_Data_Integration_Guide_x.x
# ThoughtSpot_Release_Notes_x.x
# ThoughtSpot_Application_Integration_Guide_x.x
# ThoughtSpot_Disaster_Recovery_Guide_x.x
# ThoughtSpot_User_Guide_x.x
# ThoughtSpot_Data_Connect_Guide_x.x
# ThoughtSpot_Reference_Guide_x.x
# ThoughtSpot_Node_Setup_Guide_x.x
#
destination: _site/
url: "http://127.0.0.1:4010"
baseurl: ""
port: 4010
output: pdf
product: mydoc
print_title: THETITLE
print_subtitle: Version THEVERSION
output: pdf
defaults:
  -

collections:
  admin:
    output: true
  advanced-search:
    output: true
  app-integrate:
    output: true
  appliance:
    output: true
  complex-search:
    output: true
  data-connect:
    output: true
  data-integrate:
    output: true
  disaster-recovery:
    output: true
  end-user:
    output: true
  error-codes:
    output: true
  reference:
    output: true
  release:
    output: true
  spotiq:
    output: true

defaults:
  - values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: mydoc_sidebar
